/**
 * Resource Type Normalization
 *
 * Restores canonical FHIR resource-type casing for issues created with an
 * unknown or lowercased resource type, inferring the type from the issue
 * path's first segment when the caller passed 'Unknown'.
 */

const KNOWN_RESOURCE_TYPE_BY_LOWERCASE: Record<string, string> = {
    account: 'Account',
    activitydefinition: 'ActivityDefinition',
    adverseevent: 'AdverseEvent',
    allergyintolerance: 'AllergyIntolerance',
    appointment: 'Appointment',
    appointmentresponse: 'AppointmentResponse',
    auditevent: 'AuditEvent',
    basic: 'Basic',
    binary: 'Binary',
    biologicallyderivedproduct: 'BiologicallyDerivedProduct',
    bodystructure: 'BodyStructure',
    bundle: 'Bundle',
    capabilitystatement: 'CapabilityStatement',
    careplan: 'CarePlan',
    careteam: 'CareTeam',
    catalogentry: 'CatalogEntry',
    chargeitem: 'ChargeItem',
    chargeitemdefinition: 'ChargeItemDefinition',
    claim: 'Claim',
    claimresponse: 'ClaimResponse',
    clinicalimpression: 'ClinicalImpression',
    codesystem: 'CodeSystem',
    communication: 'Communication',
    communicationrequest: 'CommunicationRequest',
    compartmentdefinition: 'CompartmentDefinition',
    composition: 'Composition',
    conceptmap: 'ConceptMap',
    condition: 'Condition',
    consent: 'Consent',
    contract: 'Contract',
    coverage: 'Coverage',
    coverageeligibilityrequest: 'CoverageEligibilityRequest',
    coverageeligibilityresponse: 'CoverageEligibilityResponse',
    detectedissue: 'DetectedIssue',
    device: 'Device',
    devicedefinition: 'DeviceDefinition',
    devicemetric: 'DeviceMetric',
    devicerequest: 'DeviceRequest',
    deviceusestatement: 'DeviceUseStatement',
    diagnosticreport: 'DiagnosticReport',
    documentmanifest: 'DocumentManifest',
    documentreference: 'DocumentReference',
    effectevidencesynthesis: 'EffectEvidenceSynthesis',
    encounter: 'Encounter',
    endpoint: 'Endpoint',
    enrollmentrequest: 'EnrollmentRequest',
    enrollmentresponse: 'EnrollmentResponse',
    episodeofcare: 'EpisodeOfCare',
    eventdefinition: 'EventDefinition',
    evidence: 'Evidence',
    evidencevariable: 'EvidenceVariable',
    examplescenario: 'ExampleScenario',
    explanationofbenefit: 'ExplanationOfBenefit',
    familymemberhistory: 'FamilyMemberHistory',
    flag: 'Flag',
    goal: 'Goal',
    graphdefinition: 'GraphDefinition',
    group: 'Group',
    guidanceresponse: 'GuidanceResponse',
    healthcareservice: 'HealthcareService',
    imagingstudy: 'ImagingStudy',
    immunization: 'Immunization',
    immunizationevaluation: 'ImmunizationEvaluation',
    immunizationrecommendation: 'ImmunizationRecommendation',
    implementationguide: 'ImplementationGuide',
    insuranceplan: 'InsurancePlan',
    invoice: 'Invoice',
    library: 'Library',
    linkage: 'Linkage',
    list: 'List',
    location: 'Location',
    measure: 'Measure',
    measurereport: 'MeasureReport',
    media: 'Media',
    medication: 'Medication',
    medicationadministration: 'MedicationAdministration',
    medicationdispense: 'MedicationDispense',
    medicationknowledge: 'MedicationKnowledge',
    medicationrequest: 'MedicationRequest',
    medicationstatement: 'MedicationStatement',
    medicinalproduct: 'MedicinalProduct',
    medicinalproductauthorization: 'MedicinalProductAuthorization',
    medicinalproductcontraindication: 'MedicinalProductContraindication',
    medicinalproductindication: 'MedicinalProductIndication',
    medicinalproductingredient: 'MedicinalProductIngredient',
    medicinalproductinteraction: 'MedicinalProductInteraction',
    medicinalproductmanufactured: 'MedicinalProductManufactured',
    medicinalproductpackaged: 'MedicinalProductPackaged',
    medicinalproductpharmaceutical: 'MedicinalProductPharmaceutical',
    medicinalproductundesirableeffect: 'MedicinalProductUndesirableEffect',
    messageheader: 'MessageHeader',
    namingsystem: 'NamingSystem',
    nutritionorder: 'NutritionOrder',
    observation: 'Observation',
    observationdefinition: 'ObservationDefinition',
    operationdefinition: 'OperationDefinition',
    operationoutcome: 'OperationOutcome',
    organization: 'Organization',
    organizationaffiliation: 'OrganizationAffiliation',
    parameters: 'Parameters',
    patient: 'Patient',
    paymentnotice: 'PaymentNotice',
    paymentreconciliation: 'PaymentReconciliation',
    person: 'Person',
    plandefinition: 'PlanDefinition',
    practitioner: 'Practitioner',
    practitionerrole: 'PractitionerRole',
    procedure: 'Procedure',
    provenance: 'Provenance',
    questionnaire: 'Questionnaire',
    questionnaireresponse: 'QuestionnaireResponse',
    relatedperson: 'RelatedPerson',
    requestgroup: 'RequestGroup',
    researchdefinition: 'ResearchDefinition',
    researchelementdefinition: 'ResearchElementDefinition',
    researchstudy: 'ResearchStudy',
    researchsubject: 'ResearchSubject',
    riskassessment: 'RiskAssessment',
    riskevidencesynthesis: 'RiskEvidenceSynthesis',
    schedule: 'Schedule',
    searchparameter: 'SearchParameter',
    servicerequest: 'ServiceRequest',
    slot: 'Slot',
    specimen: 'Specimen',
    specimendefinition: 'SpecimenDefinition',
    structuredefinition: 'StructureDefinition',
    structuremap: 'StructureMap',
    subscription: 'Subscription',
    substance: 'Substance',
    substancenucleicacid: 'SubstanceNucleicAcid',
    substancepolymer: 'SubstancePolymer',
    substanceprotein: 'SubstanceProtein',
    substancereferenceinformation: 'SubstanceReferenceInformation',
    substancesourcematerial: 'SubstanceSourceMaterial',
    substancespecification: 'SubstanceSpecification',
    supplydelivery: 'SupplyDelivery',
    supplyrequest: 'SupplyRequest',
    task: 'Task',
    terminologycapabilities: 'TerminologyCapabilities',
    testreport: 'TestReport',
    testscript: 'TestScript',
    valueset: 'ValueSet',
    verificationresult: 'VerificationResult',
    visionprescription: 'VisionPrescription',
};

function inferResourceTypeFromPath(path: string): string | undefined {
    const firstPathSegment = path.split(/[.[/:]/)[0]?.toLowerCase();
    if (!firstPathSegment) return undefined;
    return KNOWN_RESOURCE_TYPE_BY_LOWERCASE[firstPathSegment];
}

export function normalizeResourceType(resourceType: string, path: string): string {
    if (resourceType && resourceType !== 'Unknown') return resourceType;
    return inferResourceTypeFromPath(path) ?? resourceType;
}
